services:
  app:
    image: ghcr.io/aarongsellin/hit-trivia:latest
    ports:
      - '80:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - APPLE_MUSIC_TEAM_ID=${APPLE_MUSIC_TEAM_ID:?error}
      - APPLE_MUSIC_KEY_ID=${APPLE_MUSIC_KEY_ID:?error}
      - APPLE_MUSIC_PRIVATE_KEY=${APPLE_MUSIC_PRIVATE_KEY:?error}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:?error}
