server.port=8080

# Apple Music MusicKit
apple.music.team-id=${APPLE_TEAM_ID:33AF7XUK6W}
apple.music.key-id=${APPLE_KEY_ID:Q56CY9MZTH}
apple.music.private-key=${APPLE_PRIVATE_KEY:MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgs0yJX+ygIFAkuPyD4SZjJqI3kURyGCCI0+lLgWUW/o+gCgYIKoZIzj0DAQehRANCAAQcWzs3wyzNqnqXjRaSccnmtyU9xSwDBhmhKaCouai5LiLvl7LHTOvJ7dxeesHch47vsxI+9C8Ulkx9iouY417j}

logging.level.root=INFO
logging.level.com.hittrivia=DEBUG