spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hit_trivia}
spring.datasource.username=${DB_USER:hittrivia}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# Apple Music MusicKit
apple.music.team-id=${APPLE_TEAM_ID:33AF7XUK6W}
apple.music.key-id=${APPLE_KEY_ID:Q56CY9MZTH}
apple.music.private-key=${APPLE_PRIVATE_KEY:MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgs0yJX+ygIFAkuPyD4SZjJqI3kURyGCCI0+lLgWUW/o+gCgYIKoZIzj0DAQehRANCAAQcWzs3wyzNqnqXjRaSccnmtyU9xSwDBhmhKaCouai5LiLvl7LHTOvJ7dxeesHch47vsxI+9C8Ulkx9iouY417j}

logging.level.root=INFO
logging.level.com.hittrivia=DEBUG